
exec-once = waybar
exec-once = mako

exec-once = swaybg -i ~/.config/hypr/media/bg.png -m fill

bind = SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

bind = SUPER, W, killactive
bind = SUPER, RETURN, exec, alacritty
bind = SUPER SHIFT, F, exec, nautilus
bind = SUPER, O, togglefloating
bind = SUPER, SPACE, exec, rofi -show drun
bind = SUPER SHIFT, RETURN, exec, microsoft-edge-stable
bind = SUPER, F, fullscreen
bind = SUPER, ESCAPE, exec, ~/.config/hypr/scripts/powermenu.sh

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindel = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness.sh up
bindel = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness.sh down

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

input {
    kb_layout = gb
    touchpad {
        natural_scroll = true
	disable_while_typing = false
    }

}
